project_id = "rhhzsmupixdhurricppk"

[functions.tributbot-chat]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.process-news]
verify_jwt = false

[functions.fetch-news]
verify_jwt = false

[functions.send-news-alerts]
verify_jwt = false
